### ISSUE TITLE
Clickable emoticons

### ISSUE THREAD

**Issue by waskito** [JangoSteve/jQuery-CSSEmoticons#7]
Hello Steve,

I am newbie at js, and I want to create clickable emote to help user creating emote into editor (like facebook or many messenger), this is the js code I clip from : http://jsfiddle.net/JVDES/14/ .
I try to change the selector into my own selector, but failed. I try to create:
$("#emoteWrapper span.css-emoticon").click(function(){
  alert("It works!");
});
but it's still failed. Can you help me?

Thank you

**Comment by JangoSteve** [comment]
My guess is you're probably calling the above before the emoticons have loaded. Try attaching your handler to the document instead via `delegate`:

``` js
$(document).delegate('.css-emoticon', 'click', function(e) {
  var text = $(this).text();
  alert(text);
  e.preventDefault();
});
```

See [my article describing how delegate works](http://www.alfajango.com/blog/the-difference-between-jquerys-bind-live-and-delegate/).

At any rate, this is more a general javascript question rather than a css emoticons issue. Try posting on StackOverflow if you're still having issues with javascript.
