### ISSUE TITLE
Receive update if necessary?

### ISSUE THREAD

**Issue by greduan** [JangoSteve/jQuery-CSSEmoticons#8]
Hi @JangoSteve, great thing you've got going on here. :)

I found this and I gotta say it's a genius solution to a simple problem. Who needs images when you can just use CSS. :)

So I want to implement this in my website but I want to make sure it works well with today's browsers.

So this is just a friendly request for a yes or no answer, does this work with all modern browsers? Except with IE since I know there's a pull request (#4) for that.

Thanks again! :)

**Comment by JangoSteve** [comment]
In short, yes it does work with all modern browsers. It relies on the following CSS properties (links to browser support for each):
- [CSS transforms](http://caniuse.com/transforms2d) (apparently IE9 supports this with the `-ms` vendor prefix, so just one more line could make it IE9 compatible)
- [border radius](http://caniuse.com/#feat=border-radius)
- [box-shadow](http://caniuse.com/#feat=css-boxshadow)
- [CSS gradients](http://caniuse.com/#feat=css-gradients)
- [CSS transitions](http://caniuse.com/#feat=css-transitions)

Even for the browsers that don't support some of these, the emoticons are still recognizable. For example, if the browser doesn't support transforms, then the emoticons still show sideways (as typed). If the browser doesn't support CSS gradients, then they're solid yellow. If the browser doesn't support transitions, then they flip between sideways and right side up instead of gradually rotating. And if the browser doesn't support box shadows, then they simply don't have an underlying shadow.

The only support that's really needed as a minimum is border-radius, which is largely supported by now.

**Comment by greduan** [comment]
@JangoSteve Excellent! And what about the JS?

Would it work with the latest versions of jQuery? Because loading two jQuery scripts is not ideal if even possible. :)

This seems to use jQuery v1.4.2, the latest version is v1.10.2. :)

**Comment by JangoSteve** [comment]
I haven't tried it with the latest version, but I just glanced back through the code and I don't see anything in there that's been changed in jQuery, so I believe it should work with the latest.

**Comment by JangoSteve** [comment]
If it doesn't, let me know.

**Comment by greduan** [comment]
All right, I'll do just that. BBL. :)

**Comment by greduan** [comment]
OK I implemented it into my website:
https://github.com/Greduan/eduantech.docpad/blob/master/src/files/scripts/cssemoticons.min.js
https://github.com/Greduan/eduantech.docpad/blob/master/src/files/styles/cssemoticons.css

I modified them to my minimalistic needs so I pretty much made it flat, but it works. I haven't tried on IE since I'm on a Mac but I did implement the IE support fork. :)

**Comment by JangoSteve** [comment]
Awesome. I suppose we can close this out now.

**Comment by JangoSteve** [comment]
Also, FYI, you can test IE on Mac using Microsoft's free virtualbox images: http://www.modern.ie/en-us/virtualization-tools#downloads
